### ISSUE TITLE
ParseError

### ISSUE THREAD

**Issue by paddor** [vyskocilm/mkapi#1] opened 2015-12-22 01:21 UTC
Just tried [this](https://github.com/vyskocilm/zproject/commit/d1e70037cf291e0fd83848a245c9e3d3d069ef7d#commitcomment-15109202) again, but this time using `mkapi.py` from this repository.

```
$ pwd
/Users/paddor/src/python/mkapi/tests/czmq
$ python ../../mkapi.py -I~/src/python/pycparser/utils/fake_libc_include include/zsock.h
include/zsock.h:134:8: warning: missing terminating ' character [-Winvalid-pp-token]
//  isn't supported.
       ^
include/zsock.h:145:8: warning: missing terminating ' character [-Winvalid-pp-token]
//  isn't supported.
       ^
2 warnings generated.
Traceback (most recent call last):
  File "../../mkapi.py", line 327, in <module>
    main()
  File "../../mkapi.py", line 317, in main
    decls = get_func_decls(args.header, args)
  File "../../mkapi.py", line 181, in get_func_decls
    cpp_args=cpp_args)
  File "/Library/Python/2.7/site-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/Library/Python/2.7/site-packages/pycparser/c_parser.py", line 146, in parse
    debug=debuglevel)
  File "/Library/Python/2.7/site-packages/pycparser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/Library/Python/2.7/site-packages/pycparser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/Library/Python/2.7/site-packages/pycparser/c_parser.py", line 1680, in p_error
    column=self.clex.find_tok_column(p)))
  File "/Library/Python/2.7/site-packages/pycparser/plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: include/zsock.h:21:1: before: /
```

It doesn't seem to matter which header file I try to generate from.

**Comment by vyskocilm** [comment] 2015-12-22 08:15
The problem is most likely caused by internal symbols of your system C compiler (clang?) "leaking" to cpp's output. I have had the same thing on glibc/Linux and my solution was to remove them in fake_cpp post processor.

Can you please run your cpp -I /path/to/fake_libc_headers include/czmq.h and paste it's output somewhere? I will analyze which symbols are causing the parsing errors.

BTW: see pycparser's author post for deatils, if you're interested 
http://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers/

**Comment by paddor** [comment] 2015-12-22 17:06
Yeah, it's clang.

Here's what `cpp -I~/src/python/pycparser/utils/fake_libc_include include/czmq.h` tells me:
https://gist.github.com/paddor/daf565177709d6ad56ec

Thanks.

**Comment by vyskocilm** [comment] 2015-12-22 21:41
I am confused by number of hard errors. It sounds like cpp is not the clang preprocessor on your system. Can you replace cpp in fake cpp script by clang -E and try it again? If that will fail please update the gist one more time... This time with output of clang

**Comment by paddor** [comment] 2015-12-23 08:58
When I replace `cpp` with `clang -E` in `fake_cpp`, I get this:

```
Traceback (most recent call last):
  File "/Users/paddor/src/python/mkapi/mkapi.py", line 327, in <module>
    main()
  File "/Users/paddor/src/python/mkapi/mkapi.py", line 317, in main
    decls = get_func_decls(args.header, args)
  File "/Users/paddor/src/python/mkapi/mkapi.py", line 181, in get_func_decls
    cpp_args=cpp_args)
  File "/Library/Python/2.7/site-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/Library/Python/2.7/site-packages/pycparser/c_parser.py", line 146, in parse
    debug=debuglevel)
  File "/Library/Python/2.7/site-packages/pycparser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/Library/Python/2.7/site-packages/pycparser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/Library/Python/2.7/site-packages/pycparser/c_parser.py", line 1680, in p_error
    column=self.clex.find_tok_column(p)))
  File "/Library/Python/2.7/site-packages/pycparser/plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/include/i386/_types.h:98:27: before: __darwin_va_list
```

I'm not sure if I understand the last part of your comment correctly. Do you want me to run it with just `clang` now?

**Comment by paddor** [comment] 2015-12-23 08:59
`clang include/czmq.h` gives no output at all.

**Comment by vyskocilm** [comment] 2015-12-23 09:41
Replacing cpp by clang have helped. Now it fails on __darwin_va_list symbol. I will update the tool to detect system preprocessor better.

You need to call clang -E to get out up from preprocessor stage.
Thanks!

**Comment by vyskocilm** [comment] 2015-12-23 09:43
I meant _output_

**Comment by paddor** [comment] 2015-12-23 09:46
Okay, now I understood. See output [here](https://gist.github.com/paddor/78e978079b56c5aaee7a). Thanks!

**Comment by vyskocilm** [comment] 2015-12-23 16:19
Hi,

system preprocessor now defaults to clang on darwin platform.

I have analyzed the output - fake_libc_include already defines __builtin_va_list, so there should not be an issue with __darwin_va_list typedef later on. Can you please rerun the clang one more time? This time as 

```
clang -E /path/to/your/fake_libc_include include/czmq.h
```

This way I'll get the same input as pycparser

**Comment by paddor** [comment] 2015-12-23 17:28
Done, I updated the gist. Does this help?

**Comment by vyskocilm** [comment] 2015-12-23 17:42
Sorry!!! The command was supposed to be

```
clang -E -I/path/to/your/fake_libc_include include/czmq.h
```

The -I switch was missing. It is not clean if `-I /dir` variant works with clang, so please do not put the space between argument name and directory.

BTW: You can check if the command is correct by calling 

```
clang -E -I/path/to/your/fake_libc_include include/czmq.h | grep fake_libc_include 
```

If grep will return some lines like

```
# 1 "/usr/share/python-pycparser/fake_libc_include/stdlib.h" 1
# 1 "/usr/share/python-pycparser/fake_libc_include/_fake_defines.h" 1
```

then output have all the information I need to solve your problem. If there won't be fake_libc_include mentioned, then it was not included correctly.

BTW: I've checked your first comment once a time - it might be  `~` is not expanded correctly. You can try to use absolute path instead.

Thanks for your help!

**Comment by paddor** [comment] 2015-12-23 20:39
Now I'm confident it worked. You're right, the `~` won't get expanded at that position. But using

```
clang -E -I$HOME/src/python/pycparser/utils/fake_libc_include include/czmq.h
```

it works as desired.

I updated the [gist](https://gist.github.com/paddor/78e978079b56c5aaee7a).

**Comment by vyskocilm** [comment] 2015-12-24 13:48
Hi. It should work now. Please try later git from project.

**Comment by vyskocilm** [comment] 2016-01-03 12:49
Hi, fixed to my best knowledge, so I am closing this issue. Feel free to open a new one at zeromq/zproject if you will hit a bug. Thanks!

**Closed as completed by vyskocilm** 2016-01-03 12:49 UTC
